<?php
date_default_timezone_set("UTC");
define('__APP__', __DIR__ . '/..');
try {
    require __APP__ . '/vendor/autoload.php';
} catch (\Framework\Exception\FrameworkException $e) {
}
use Framework\DB\DB;

/**
 * Created by PhpStorm.
 * User: michael
 * Date: 10/19/15
 * Time: 11:20
 */
class DBDeleteTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DB
     */
    private $db;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->db = DB::connection("read");
    }


    public function testDelete() {
        $result = $this->db->delete("delete from test where id=?;",
            array(1));

        $this->assertTrue($result>0);
    }
    public function testDeleteMultipleLines() {
        $result = $this->db->delete("
        delete from test
        where id=?;",
            array(2));

        $this->assertTrue($result>0);
    }
}
