<?php
use Framework\DB\DB;

/**
 * Created by PhpStorm.
 * User: michael
 * Date: 10/19/15
 * Time: 11:20
 */
class DBDeleteTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DB
     */
    private $db;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->db = DB::connection("read");
    }


    public function testDelete() {

        $id = $this->db->insert("insert into test(name,age,adress,is_active,created_at) VALUE (?,?,?,?,now());",
            array("ssss","22","ddsdsd","1"));

        $result = $this->db->delete("delete from test where id=?;",
            array($id));

        $this->assertTrue($result>0);
    }
    public function testDeleteMultipleLines() {
        $id = $this->db->insert("insert into test(name,age,adress,is_active,created_at) VALUE (?,?,?,?,now());",
            array("ssss","22","ddsdsd","1"));

        $result = $this->db->delete("
        delete from test
        where id=?;",
            array($id));

        $this->assertTrue($result>0);
    }
}
