<?php


define('__APP__', __DIR__ . '/..');
date_default_timezone_set("UTC");
try {
    require __APP__ . '/vendor/autoload.php';
} catch (\Framework\Exception\FrameworkException $e) {
}

use Framework\DB\DB;

/**
 * Created by PhpStorm.
 * User: michael
 * Date: 10/19/15
 * Time: 11:20
 */
class DBSelectTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DB
     */
    private $db;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->db = DB::connection("read");
    }


    public function testUpperCase() {
        $result = $this->db->select("SELECT * FROM test");

        $this->assertTrue(is_array($result));
    }
    public function testNormalCase() {
        $result = $this->db->select("select * from test");

        $this->assertTrue(is_array($result));
    }
    public function testFetchObjectMode() {
        $this->db->setFetchMode(PDO::FETCH_OBJ);

        $result = $this->db->select("select * from test");

        $this->assertTrue(is_array($result));

        foreach ($result   as $obj) {
            $this->assertTrue(is_object($obj));
        }
    }
    public function testFetchArrayMode(){
        $this->db->setFetchMode(PDO::FETCH_ASSOC);

        $result = $this->db->select("select * from test");

        $this->assertTrue(is_array($result));

        foreach ($result   as $obj) {
            $this->assertTrue(is_array($obj));
        }
    }

    public function testMultiLinesQuery() {
        $result = $this->db->select("
        select *
        from test");
        $this->assertTrue(is_array($result));
    }
}
