<?php
date_default_timezone_set("UTC");
define('__APP__', __DIR__ . '/..');
try {
    require __APP__ . '/vendor/autoload.php';
} catch (\Framework\Exception\FrameworkException $e) {
}

use Framework\DB\DB;

/**
 * Created by PhpStorm.
 * User: michael
 * Date: 10/19/15
 * Time: 11:20
 */
class DBUpdateTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DB
     */
    private $db;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->db = DB::connection("read");
    }


    public function testUpdate() {
        $result = $this->db->update("update test set name=?,age=?;",
            array("ssss","22"));

        $this->assertTrue($result>0);
    }
    public function testUpdateMultipleLines() {
        $result = $this->db->update("
        update test
        set name=?,age=? where id=?;",
            array("dddd","2222",1));

        $this->assertTrue($result>0);
    }

}
